import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * The rule that matters here is the Prisma boundary in the third block.
 * Everything else is ordinary hygiene.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "docs/spikes/**",
      "**/*.config.js",
      "**/*.config.mjs",
      "**/*.config.mts",
      // Generated by `prisma generate`; carries its own eslint-disable and
      // @ts-nocheck. Never edited by hand.
      "apps/api/src/generated/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always"],
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ★ The repository boundary.
  //
  // Prisma gives none of the safety Django's ORM gave for free. A query that
  // forgets `deletedAt: null` returns deleted records; one that forgets the
  // tenant filter returns ANOTHER KINDERGARTEN'S CHILDREN. Confining Prisma to
  // repository files keeps those filters in a handful of reviewable places
  // rather than at every call site in the codebase.
  //
  // A convention nobody enforces is a convention that lasts until the first
  // deadline. This is the enforcement.
  //
  // CLAUDE.md §2.2 · docs/ARCHITECTURE.md §4.1 · docs/SECURITY.md §8
  // ─────────────────────────────────────────────────────────────────────────
  {
    files: ["apps/api/src/**/*.ts"],
    ignores: [
      "apps/api/src/**/*.repository.ts",
      "apps/api/src/prisma/prisma.service.ts",
      "apps/api/src/common/repository/**",
      // The single sanctioned seam for re-exporting generated enums. See the
      // file's own comment for why an exception here beats weakening the rule.
      "apps/api/src/domain/enums.ts",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@prisma/client",
              message:
                "Prisma may only be imported from *.repository.ts or src/prisma/prisma.service.ts. " +
                "Services and controllers must go through a repository, which applies the tenant " +
                "and soft-delete filters. See CLAUDE.md §2.2.",
            },
            {
              name: "@prisma/adapter-pg",
              message: "The database adapter is constructed once, in PrismaService.",
            },
          ],
          patterns: [
            {
              // The generated client — the actual query surface under Prisma 7.
              //
              // `generated/prisma/enums` is deliberately NOT blocked. It exports
              // plain constants (Role, ChildStatus …) with no query capability,
              // and authorization code legitimately needs to compare against
              // them. Blocking it would push callers into re-declaring the enum
              // by hand, which drifts from the schema silently — a worse outcome
              // than the thing the rule is protecting against.
              // The whole generated directory, with no carve-outs. Code that
              // needs a domain enum imports it from src/domain/enums.ts, which
              // is the one file exempted above.
              group: ["**/generated/prisma", "**/generated/prisma/**"],
              message:
                "Prisma may only be imported from *.repository.ts or src/prisma/prisma.service.ts. " +
                "See CLAUDE.md §2.2. (generated/prisma/enums is allowed — it carries no query access.)",
            },
            {
              // The subtler bypass: not importing Prisma, but injecting the
              // service that wraps it — same unfiltered access, different line.
              group: ["**/prisma/prisma.service", "**/prisma/prisma.service.js"],
              message:
                "Inject PrismaService into a repository, not into a service or controller. " +
                "See CLAUDE.md §2.2.",
            },
          ],
        },
      ],
    },
  },

  // Test files legitimately reach for internals.
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "**/test/**"],
    rules: {
      "no-restricted-imports": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

  // CLI scripts. Printing to stdout is their entire interface — a seed that
  // reports nothing is a seed you cannot tell succeeded. They also construct
  // their own Prisma client legitimately, running outside Nest's DI container.
  {
    files: ["apps/api/prisma/**/*.ts"],
    rules: {
      "no-console": "off",
      "no-restricted-imports": "off",
    },
  },

  // Operator scripts — `reset-password`, `setup-test-db`. Same argument for
  // stdout as the seeds above, and deliberately NOT the same exemption for
  // Prisma: these run against real databases, so if one ever needs a client it
  // should have to justify that rather than inherit permission from a glob.
  {
    files: ["apps/api/scripts/**/*.ts"],
    rules: {
      "no-console": "off",
    },
  },
);
